name: ci
"on":
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm tsc
      - run: pnpm build
      - name: pnpm test
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' pnpm test
      - name: pnpm test-e2e
        run: xvfb-run --auto-servernum --server-args='-screen 0 1920x1080x24' pnpm test-e2e
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          path: test-results
