name: ci
"on":
  - push
jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.9.5"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.17.0"
      - run: pnpm i --frozen-lockfile
      - run: npm run lint:check
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: "7.9.5"
      - uses: actions/setup-node@v2
        with:
          node-version: "16.17.0"
      - run: pnpm i --frozen-lockfile
      - run: npm run tsc
      - uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm run test
