name: ci
"on":
  - push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: pnpm i
      - run: pnpm lint-check
      - run: pnpm tsc
      - run: pnpm build
      - name: pnpm test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: pnpm test
