name: release
on:
  push:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 20
      - run: pnpm i
      - run: pnpm release
        env:
          VSCE_PAT: ""
