name: release
on:
  workflow_dispatch:
jobs:
  release:
    runs-on: ubuntu-latest
    environment:
      name: release
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: pnpm i
      - run: pnpm build
      - run: cd dist/package && npx vsce publish
        env:
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
